### ISSUE TITLE
Create separate sign up and sign in forms

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Youdemy#1]
![image](https://github.com/ContriHUB/Youdemy/assets/59749539/4c44f9e3-dab0-468a-a4f2-a6601db8afb9)

### Problem

Currently, there is a single form and one view (main.views.account) that is used for both sign up and sign in which is not very user friendly

### Expected behaviour

Create separate forms for sign in (add 2 fields for user name and password just below the sign up button and modify views accordingly)
Also add a role field to user model and allow a user to register as a "Student" or "Mentor" (Use radio buttons or dropdown)
Please follow the existing theme of website

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted

**Comment by echohint1** [comment]
Hello sir, I have read the problem and i want to work on this problem. so sir pls assign it to me.

**Comment by kunal2812** [comment]
Please request on Contrihub

**Comment by yash037** [comment]
@kunal2812 can you assign me this issue?

**Comment by eleensmathew** [comment]
Can I get an extra day to complete this issue?

**Comment by kunal2812** [comment]
Not sure if re-requesting for the same issue is allowed

**Comment by eleensmathew** [comment]
Is it fine if i submit an incomplete pull request then? and finsish the changes the day after?

**Comment by kunal2812** [comment]
Yes you can but try to fix it as early as possible. You still have 7 hrs left for this issue.
