### ISSUE TITLE
Implement Project Creation Functionality for Mentors

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Youdemy#18]
![image](https://github.com/ContriHUB/Youdemy/assets/59749539/038c0d9b-29a3-41aa-a382-df39fe7d68b3)

Currently "Project" page is static.
Introduce the ability for users with the "Mentor" role to create and share projects. These projects should be structured and must include essential components such as:
- Project Heading
- Project Introduction
- Video Tutorial (with a video upload option or video URL)
- Step-by-Step Procedure (with text and image upload options)
- Full Code (with code formatting options)
- Conclusion

Allow Mentors to save project drafts and edit them before and after publication to ensure content quality and appropriateness. Make the projects viewable by all users on the "Project" page. Ensure that the project creation form and project viewing pages are responsive.

Update user documentation to provide guidance on how Mentors can create, edit, and manage projects, as well as how all users can access and utilize project resources.

Reference:
https://medium.com/bukalapak-data/one-easy-way-to-develop-your-own-chatbot-dacdb231957c

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted
- Follow the existing theme of website
- Don't request for the issue if it has locked label on it (will be unlocked after dependencies are fixed)

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by kunal2812** [comment]
Assigned to @eleensmathew

**Comment by eleensmathew** [comment]
Does the full code with formatting options kind of look like this 
![image](https://github.com/ContriHUB/Youdemy/assets/92302620/4d99eef5-5702-426a-ae4e-027d4e6569e9)
if not can you provide more reference and can you provide some material how to implement this?

**Comment by kunal2812** [comment]
Check [this](https://clt.champlain.edu/kb/inserting-code-snippets/#:~:text=Because%20your%20code%20is%20the,%3D%E2%80%9Dline%2Dnumbers%E2%80%9D.) out

**Comment by eleensmathew** [comment]
is this ok ?
![image](https://github.com/ContriHUB/Youdemy/assets/92302620/c5e1e131-acc4-4658-8144-1b1490e7b458)

**Comment by kunal2812** [comment]
> is this ok ? ![image](https://user-images.githubusercontent.com/92302620/279190910-c5e1e131-acc4-4658-8144-1b1490e7b458.png)

Yes

**Comment by eleensmathew** [comment]
Do you want the project card look similar to blog card? to keep all the element have same height and consistent project card heights and the read more part?

**Comment by kunal2812** [comment]
> Do you want the project card look similar to blog card? to keep all the element have same height and consistent project card heights and the read more part?

As shown in the screenshot above. Language of the project should be there. 1 line heading and 4 line project introduction preview.
