### ISSUE TITLE
Implement "Add a course" functionality for Mentors

### ISSUE THREAD

**Issue by kunal2812** [ContriHUB/Youdemy#4]
Courses can only be added by Users with role "Mentor" (View static page /courses)
![image](https://github.com/ContriHUB/Youdemy/assets/59749539/1dfeb89c-5886-4548-aa6a-2e35cf38bc4b)

A course has several chapters (View static page /course1)
![image](https://github.com/ContriHUB/Youdemy/assets/59749539/0dd248d5-f7b9-454a-820c-82cc33f4ff3d)

A chapter has several topics and questions (View static page /chapter1)
![image](https://github.com/ContriHUB/Youdemy/assets/59749539/97e67c88-79e4-4ade-be4e-4add9bb2a28d)

Note:

- Create a new branch for every task to isolate changes
- Start working on the issue only when it is assigned to you
- Submit the PR on time, no extra time will be allotted
- Follow the existing theme of website
- Don't request for the issue if it has locked label on it (will be unlocked after dependencies are fixed)

**Comment by eleensmathew** [comment]
Can i be assigned this?

**Comment by kunal2812** [comment]
Dependent on issue 1. Will be fixed by tonight

**Comment by kunal2812** [comment]
Issue 1 is not fixed and open now. @eleensmathew Do you want me to reject your request for this issue ?

**Comment by eleensmathew** [comment]
Can i do both?

**Comment by kunal2812** [comment]
Yes

**Comment by eleensmathew** [comment]
cool 👍

**Comment by eleensmathew** [comment]
can i be assigned this now?

**Comment by kunal2812** [comment]
Already assigned to you

**Comment by eleensmathew** [comment]
Should there be a one to many relation between mentor and courses?

**Comment by kunal2812** [comment]
Yes

**Comment by eleensmathew** [comment]
If a mentor is adding a course should it immediately be available for it to be seen by all the users? so should I just save that info to a field labeling it as 'editing' until mentor finally decides to publish that course? What i mean is, in most sites the mentor would usually only publish near perfect courses so to do this we need to provide some functionality for mentors to review the course or keep adding to it until they feel its perfect. So one way we can do this is to make a separate page for mentors to see the courses they are working on and edit them and when they publish that course that field will be marked as 'completed'. Still the mentor will have editing options after the course is 'completed'. So i go with this approach or should i leave it?

**Comment by kunal2812** [comment]
If its possible for you to work on this "Currently editing" approach then you can work on it or else you can allow direct publishing of course. Bonus points will be given according to your efforts.

**Comment by eleensmathew** [comment]
I will try my level best.
